# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rafael/NetBeans/CompetitionNB

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rafael/NetBeans/CompetitionNB

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rafael/NetBeans/CompetitionNB/CMakeFiles /home/rafael/NetBeans/CompetitionNB/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rafael/NetBeans/CompetitionNB/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CompetitionNB.app

# Build rule for target.
CompetitionNB.app: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CompetitionNB.app
.PHONY : CompetitionNB.app

# fast build rule for target.
CompetitionNB.app/fast:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/build
.PHONY : CompetitionNB.app/fast

#=============================================================================
# Target rules for targets named dlib

# Build rule for target.
dlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dlib
.PHONY : dlib

# fast build rule for target.
dlib/fast:
	$(MAKE) -f dlib_build/CMakeFiles/dlib.dir/build.make dlib_build/CMakeFiles/dlib.dir/build
.PHONY : dlib/fast

src/Annotation.o: src/Annotation.cpp.o
.PHONY : src/Annotation.o

# target to build an object file
src/Annotation.cpp.o:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/Annotation.cpp.o
.PHONY : src/Annotation.cpp.o

src/Annotation.i: src/Annotation.cpp.i
.PHONY : src/Annotation.i

# target to preprocess a source file
src/Annotation.cpp.i:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/Annotation.cpp.i
.PHONY : src/Annotation.cpp.i

src/Annotation.s: src/Annotation.cpp.s
.PHONY : src/Annotation.s

# target to generate assembly for a file
src/Annotation.cpp.s:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/Annotation.cpp.s
.PHONY : src/Annotation.cpp.s

src/Cell.o: src/Cell.cpp.o
.PHONY : src/Cell.o

# target to build an object file
src/Cell.cpp.o:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/Cell.cpp.o
.PHONY : src/Cell.cpp.o

src/Cell.i: src/Cell.cpp.i
.PHONY : src/Cell.i

# target to preprocess a source file
src/Cell.cpp.i:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/Cell.cpp.i
.PHONY : src/Cell.cpp.i

src/Cell.s: src/Cell.cpp.s
.PHONY : src/Cell.s

# target to generate assembly for a file
src/Cell.cpp.s:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/Cell.cpp.s
.PHONY : src/Cell.cpp.s

src/Collection.o: src/Collection.cpp.o
.PHONY : src/Collection.o

# target to build an object file
src/Collection.cpp.o:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/Collection.cpp.o
.PHONY : src/Collection.cpp.o

src/Collection.i: src/Collection.cpp.i
.PHONY : src/Collection.i

# target to preprocess a source file
src/Collection.cpp.i:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/Collection.cpp.i
.PHONY : src/Collection.cpp.i

src/Collection.s: src/Collection.cpp.s
.PHONY : src/Collection.s

# target to generate assembly for a file
src/Collection.cpp.s:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/Collection.cpp.s
.PHONY : src/Collection.cpp.s

src/ColorHistogram.o: src/ColorHistogram.cpp.o
.PHONY : src/ColorHistogram.o

# target to build an object file
src/ColorHistogram.cpp.o:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/ColorHistogram.cpp.o
.PHONY : src/ColorHistogram.cpp.o

src/ColorHistogram.i: src/ColorHistogram.cpp.i
.PHONY : src/ColorHistogram.i

# target to preprocess a source file
src/ColorHistogram.cpp.i:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/ColorHistogram.cpp.i
.PHONY : src/ColorHistogram.cpp.i

src/ColorHistogram.s: src/ColorHistogram.cpp.s
.PHONY : src/ColorHistogram.s

# target to generate assembly for a file
src/ColorHistogram.cpp.s:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/ColorHistogram.cpp.s
.PHONY : src/ColorHistogram.cpp.s

src/Component.o: src/Component.cpp.o
.PHONY : src/Component.o

# target to build an object file
src/Component.cpp.o:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/Component.cpp.o
.PHONY : src/Component.cpp.o

src/Component.i: src/Component.cpp.i
.PHONY : src/Component.i

# target to preprocess a source file
src/Component.cpp.i:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/Component.cpp.i
.PHONY : src/Component.cpp.i

src/Component.s: src/Component.cpp.s
.PHONY : src/Component.s

# target to generate assembly for a file
src/Component.cpp.s:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/Component.cpp.s
.PHONY : src/Component.cpp.s

src/CompoundLocalBinaryPattern.o: src/CompoundLocalBinaryPattern.cpp.o
.PHONY : src/CompoundLocalBinaryPattern.o

# target to build an object file
src/CompoundLocalBinaryPattern.cpp.o:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/CompoundLocalBinaryPattern.cpp.o
.PHONY : src/CompoundLocalBinaryPattern.cpp.o

src/CompoundLocalBinaryPattern.i: src/CompoundLocalBinaryPattern.cpp.i
.PHONY : src/CompoundLocalBinaryPattern.i

# target to preprocess a source file
src/CompoundLocalBinaryPattern.cpp.i:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/CompoundLocalBinaryPattern.cpp.i
.PHONY : src/CompoundLocalBinaryPattern.cpp.i

src/CompoundLocalBinaryPattern.s: src/CompoundLocalBinaryPattern.cpp.s
.PHONY : src/CompoundLocalBinaryPattern.s

# target to generate assembly for a file
src/CompoundLocalBinaryPattern.cpp.s:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/CompoundLocalBinaryPattern.cpp.s
.PHONY : src/CompoundLocalBinaryPattern.cpp.s

src/Face.o: src/Face.cpp.o
.PHONY : src/Face.o

# target to build an object file
src/Face.cpp.o:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/Face.cpp.o
.PHONY : src/Face.cpp.o

src/Face.i: src/Face.cpp.i
.PHONY : src/Face.i

# target to preprocess a source file
src/Face.cpp.i:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/Face.cpp.i
.PHONY : src/Face.cpp.i

src/Face.s: src/Face.cpp.s
.PHONY : src/Face.s

# target to generate assembly for a file
src/Face.cpp.s:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/Face.cpp.s
.PHONY : src/Face.cpp.s

src/GaborFilter.o: src/GaborFilter.cpp.o
.PHONY : src/GaborFilter.o

# target to build an object file
src/GaborFilter.cpp.o:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/GaborFilter.cpp.o
.PHONY : src/GaborFilter.cpp.o

src/GaborFilter.i: src/GaborFilter.cpp.i
.PHONY : src/GaborFilter.i

# target to preprocess a source file
src/GaborFilter.cpp.i:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/GaborFilter.cpp.i
.PHONY : src/GaborFilter.cpp.i

src/GaborFilter.s: src/GaborFilter.cpp.s
.PHONY : src/GaborFilter.s

# target to generate assembly for a file
src/GaborFilter.cpp.s:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/GaborFilter.cpp.s
.PHONY : src/GaborFilter.cpp.s

src/HistogramOrientedGradient.o: src/HistogramOrientedGradient.cpp.o
.PHONY : src/HistogramOrientedGradient.o

# target to build an object file
src/HistogramOrientedGradient.cpp.o:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/HistogramOrientedGradient.cpp.o
.PHONY : src/HistogramOrientedGradient.cpp.o

src/HistogramOrientedGradient.i: src/HistogramOrientedGradient.cpp.i
.PHONY : src/HistogramOrientedGradient.i

# target to preprocess a source file
src/HistogramOrientedGradient.cpp.i:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/HistogramOrientedGradient.cpp.i
.PHONY : src/HistogramOrientedGradient.cpp.i

src/HistogramOrientedGradient.s: src/HistogramOrientedGradient.cpp.s
.PHONY : src/HistogramOrientedGradient.s

# target to generate assembly for a file
src/HistogramOrientedGradient.cpp.s:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/HistogramOrientedGradient.cpp.s
.PHONY : src/HistogramOrientedGradient.cpp.s

src/ImageSet.o: src/ImageSet.cpp.o
.PHONY : src/ImageSet.o

# target to build an object file
src/ImageSet.cpp.o:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/ImageSet.cpp.o
.PHONY : src/ImageSet.cpp.o

src/ImageSet.i: src/ImageSet.cpp.i
.PHONY : src/ImageSet.i

# target to preprocess a source file
src/ImageSet.cpp.i:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/ImageSet.cpp.i
.PHONY : src/ImageSet.cpp.i

src/ImageSet.s: src/ImageSet.cpp.s
.PHONY : src/ImageSet.s

# target to generate assembly for a file
src/ImageSet.cpp.s:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/ImageSet.cpp.s
.PHONY : src/ImageSet.cpp.s

src/Label.o: src/Label.cpp.o
.PHONY : src/Label.o

# target to build an object file
src/Label.cpp.o:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/Label.cpp.o
.PHONY : src/Label.cpp.o

src/Label.i: src/Label.cpp.i
.PHONY : src/Label.i

# target to preprocess a source file
src/Label.cpp.i:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/Label.cpp.i
.PHONY : src/Label.cpp.i

src/Label.s: src/Label.cpp.s
.PHONY : src/Label.s

# target to generate assembly for a file
src/Label.cpp.s:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/Label.cpp.s
.PHONY : src/Label.cpp.s

src/LocalBinaryPattern.o: src/LocalBinaryPattern.cpp.o
.PHONY : src/LocalBinaryPattern.o

# target to build an object file
src/LocalBinaryPattern.cpp.o:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/LocalBinaryPattern.cpp.o
.PHONY : src/LocalBinaryPattern.cpp.o

src/LocalBinaryPattern.i: src/LocalBinaryPattern.cpp.i
.PHONY : src/LocalBinaryPattern.i

# target to preprocess a source file
src/LocalBinaryPattern.cpp.i:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/LocalBinaryPattern.cpp.i
.PHONY : src/LocalBinaryPattern.cpp.i

src/LocalBinaryPattern.s: src/LocalBinaryPattern.cpp.s
.PHONY : src/LocalBinaryPattern.s

# target to generate assembly for a file
src/LocalBinaryPattern.cpp.s:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/LocalBinaryPattern.cpp.s
.PHONY : src/LocalBinaryPattern.cpp.s

src/Matrix.o: src/Matrix.cpp.o
.PHONY : src/Matrix.o

# target to build an object file
src/Matrix.cpp.o:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/Matrix.cpp.o
.PHONY : src/Matrix.cpp.o

src/Matrix.i: src/Matrix.cpp.i
.PHONY : src/Matrix.i

# target to preprocess a source file
src/Matrix.cpp.i:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/Matrix.cpp.i
.PHONY : src/Matrix.cpp.i

src/Matrix.s: src/Matrix.cpp.s
.PHONY : src/Matrix.s

# target to generate assembly for a file
src/Matrix.cpp.s:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/Matrix.cpp.s
.PHONY : src/Matrix.cpp.s

src/MeanIntensity.o: src/MeanIntensity.cpp.o
.PHONY : src/MeanIntensity.o

# target to build an object file
src/MeanIntensity.cpp.o:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/MeanIntensity.cpp.o
.PHONY : src/MeanIntensity.cpp.o

src/MeanIntensity.i: src/MeanIntensity.cpp.i
.PHONY : src/MeanIntensity.i

# target to preprocess a source file
src/MeanIntensity.cpp.i:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/MeanIntensity.cpp.i
.PHONY : src/MeanIntensity.cpp.i

src/MeanIntensity.s: src/MeanIntensity.cpp.s
.PHONY : src/MeanIntensity.s

# target to generate assembly for a file
src/MeanIntensity.cpp.s:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/MeanIntensity.cpp.s
.PHONY : src/MeanIntensity.cpp.s

src/PLSclassifier.o: src/PLSclassifier.cpp.o
.PHONY : src/PLSclassifier.o

# target to build an object file
src/PLSclassifier.cpp.o:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/PLSclassifier.cpp.o
.PHONY : src/PLSclassifier.cpp.o

src/PLSclassifier.i: src/PLSclassifier.cpp.i
.PHONY : src/PLSclassifier.i

# target to preprocess a source file
src/PLSclassifier.cpp.i:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/PLSclassifier.cpp.i
.PHONY : src/PLSclassifier.cpp.i

src/PLSclassifier.s: src/PLSclassifier.cpp.s
.PHONY : src/PLSclassifier.s

# target to generate assembly for a file
src/PLSclassifier.cpp.s:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/PLSclassifier.cpp.s
.PHONY : src/PLSclassifier.cpp.s

src/PLSregression.o: src/PLSregression.cpp.o
.PHONY : src/PLSregression.o

# target to build an object file
src/PLSregression.cpp.o:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/PLSregression.cpp.o
.PHONY : src/PLSregression.cpp.o

src/PLSregression.i: src/PLSregression.cpp.i
.PHONY : src/PLSregression.i

# target to preprocess a source file
src/PLSregression.cpp.i:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/PLSregression.cpp.i
.PHONY : src/PLSregression.cpp.i

src/PLSregression.s: src/PLSregression.cpp.s
.PHONY : src/PLSregression.s

# target to generate assembly for a file
src/PLSregression.cpp.s:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/PLSregression.cpp.s
.PHONY : src/PLSregression.cpp.s

src/PatternOrientedEdgeMagnitude.o: src/PatternOrientedEdgeMagnitude.cpp.o
.PHONY : src/PatternOrientedEdgeMagnitude.o

# target to build an object file
src/PatternOrientedEdgeMagnitude.cpp.o:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/PatternOrientedEdgeMagnitude.cpp.o
.PHONY : src/PatternOrientedEdgeMagnitude.cpp.o

src/PatternOrientedEdgeMagnitude.i: src/PatternOrientedEdgeMagnitude.cpp.i
.PHONY : src/PatternOrientedEdgeMagnitude.i

# target to preprocess a source file
src/PatternOrientedEdgeMagnitude.cpp.i:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/PatternOrientedEdgeMagnitude.cpp.i
.PHONY : src/PatternOrientedEdgeMagnitude.cpp.i

src/PatternOrientedEdgeMagnitude.s: src/PatternOrientedEdgeMagnitude.cpp.s
.PHONY : src/PatternOrientedEdgeMagnitude.s

# target to generate assembly for a file
src/PatternOrientedEdgeMagnitude.cpp.s:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/PatternOrientedEdgeMagnitude.cpp.s
.PHONY : src/PatternOrientedEdgeMagnitude.cpp.s

src/SlideWindow.o: src/SlideWindow.cpp.o
.PHONY : src/SlideWindow.o

# target to build an object file
src/SlideWindow.cpp.o:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/SlideWindow.cpp.o
.PHONY : src/SlideWindow.cpp.o

src/SlideWindow.i: src/SlideWindow.cpp.i
.PHONY : src/SlideWindow.i

# target to preprocess a source file
src/SlideWindow.cpp.i:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/SlideWindow.cpp.i
.PHONY : src/SlideWindow.cpp.i

src/SlideWindow.s: src/SlideWindow.cpp.s
.PHONY : src/SlideWindow.s

# target to generate assembly for a file
src/SlideWindow.cpp.s:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/SlideWindow.cpp.s
.PHONY : src/SlideWindow.cpp.s

src/UStandardDeviation.o: src/UStandardDeviation.cpp.o
.PHONY : src/UStandardDeviation.o

# target to build an object file
src/UStandardDeviation.cpp.o:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/UStandardDeviation.cpp.o
.PHONY : src/UStandardDeviation.cpp.o

src/UStandardDeviation.i: src/UStandardDeviation.cpp.i
.PHONY : src/UStandardDeviation.i

# target to preprocess a source file
src/UStandardDeviation.cpp.i:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/UStandardDeviation.cpp.i
.PHONY : src/UStandardDeviation.cpp.i

src/UStandardDeviation.s: src/UStandardDeviation.cpp.s
.PHONY : src/UStandardDeviation.s

# target to generate assembly for a file
src/UStandardDeviation.cpp.s:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/UStandardDeviation.cpp.s
.PHONY : src/UStandardDeviation.cpp.s

src/Useful.o: src/Useful.cpp.o
.PHONY : src/Useful.o

# target to build an object file
src/Useful.cpp.o:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/Useful.cpp.o
.PHONY : src/Useful.cpp.o

src/Useful.i: src/Useful.cpp.i
.PHONY : src/Useful.i

# target to preprocess a source file
src/Useful.cpp.i:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/Useful.cpp.i
.PHONY : src/Useful.cpp.i

src/Useful.s: src/Useful.cpp.s
.PHONY : src/Useful.s

# target to generate assembly for a file
src/Useful.cpp.s:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/Useful.cpp.s
.PHONY : src/Useful.cpp.s

src/ZeroMean.o: src/ZeroMean.cpp.o
.PHONY : src/ZeroMean.o

# target to build an object file
src/ZeroMean.cpp.o:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/ZeroMean.cpp.o
.PHONY : src/ZeroMean.cpp.o

src/ZeroMean.i: src/ZeroMean.cpp.i
.PHONY : src/ZeroMean.i

# target to preprocess a source file
src/ZeroMean.cpp.i:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/ZeroMean.cpp.i
.PHONY : src/ZeroMean.cpp.i

src/ZeroMean.s: src/ZeroMean.cpp.s
.PHONY : src/ZeroMean.s

# target to generate assembly for a file
src/ZeroMean.cpp.s:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/ZeroMean.cpp.s
.PHONY : src/ZeroMean.cpp.s

src/ZeroScore.o: src/ZeroScore.cpp.o
.PHONY : src/ZeroScore.o

# target to build an object file
src/ZeroScore.cpp.o:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/ZeroScore.cpp.o
.PHONY : src/ZeroScore.cpp.o

src/ZeroScore.i: src/ZeroScore.cpp.i
.PHONY : src/ZeroScore.i

# target to preprocess a source file
src/ZeroScore.cpp.i:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/ZeroScore.cpp.i
.PHONY : src/ZeroScore.cpp.i

src/ZeroScore.s: src/ZeroScore.cpp.s
.PHONY : src/ZeroScore.s

# target to generate assembly for a file
src/ZeroScore.cpp.s:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/ZeroScore.cpp.s
.PHONY : src/ZeroScore.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/CompetitionNB.app.dir/build.make CMakeFiles/CompetitionNB.app.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... CompetitionNB.app"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... dlib"
	@echo "... src/Annotation.o"
	@echo "... src/Annotation.i"
	@echo "... src/Annotation.s"
	@echo "... src/Cell.o"
	@echo "... src/Cell.i"
	@echo "... src/Cell.s"
	@echo "... src/Collection.o"
	@echo "... src/Collection.i"
	@echo "... src/Collection.s"
	@echo "... src/ColorHistogram.o"
	@echo "... src/ColorHistogram.i"
	@echo "... src/ColorHistogram.s"
	@echo "... src/Component.o"
	@echo "... src/Component.i"
	@echo "... src/Component.s"
	@echo "... src/CompoundLocalBinaryPattern.o"
	@echo "... src/CompoundLocalBinaryPattern.i"
	@echo "... src/CompoundLocalBinaryPattern.s"
	@echo "... src/Face.o"
	@echo "... src/Face.i"
	@echo "... src/Face.s"
	@echo "... src/GaborFilter.o"
	@echo "... src/GaborFilter.i"
	@echo "... src/GaborFilter.s"
	@echo "... src/HistogramOrientedGradient.o"
	@echo "... src/HistogramOrientedGradient.i"
	@echo "... src/HistogramOrientedGradient.s"
	@echo "... src/ImageSet.o"
	@echo "... src/ImageSet.i"
	@echo "... src/ImageSet.s"
	@echo "... src/Label.o"
	@echo "... src/Label.i"
	@echo "... src/Label.s"
	@echo "... src/LocalBinaryPattern.o"
	@echo "... src/LocalBinaryPattern.i"
	@echo "... src/LocalBinaryPattern.s"
	@echo "... src/Matrix.o"
	@echo "... src/Matrix.i"
	@echo "... src/Matrix.s"
	@echo "... src/MeanIntensity.o"
	@echo "... src/MeanIntensity.i"
	@echo "... src/MeanIntensity.s"
	@echo "... src/PLSclassifier.o"
	@echo "... src/PLSclassifier.i"
	@echo "... src/PLSclassifier.s"
	@echo "... src/PLSregression.o"
	@echo "... src/PLSregression.i"
	@echo "... src/PLSregression.s"
	@echo "... src/PatternOrientedEdgeMagnitude.o"
	@echo "... src/PatternOrientedEdgeMagnitude.i"
	@echo "... src/PatternOrientedEdgeMagnitude.s"
	@echo "... src/SlideWindow.o"
	@echo "... src/SlideWindow.i"
	@echo "... src/SlideWindow.s"
	@echo "... src/UStandardDeviation.o"
	@echo "... src/UStandardDeviation.i"
	@echo "... src/UStandardDeviation.s"
	@echo "... src/Useful.o"
	@echo "... src/Useful.i"
	@echo "... src/Useful.s"
	@echo "... src/ZeroMean.o"
	@echo "... src/ZeroMean.i"
	@echo "... src/ZeroMean.s"
	@echo "... src/ZeroScore.o"
	@echo "... src/ZeroScore.i"
	@echo "... src/ZeroScore.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

